### ISSUE TITLE
team106-review

### ISSUE THREAD

**Issue by kiptubei** [chelmerrox/Project-7-Using-Bootstrap#1]
Hello Losalini,

- Make use of pre-defined bootstrap grid tags to order your columns and sections for lg,md and sm screens.
- Use a toggle-collapse tag to generate the menu bar in mobile screen size.
- The aim of the project is to demonstrate mastery of bootstrap so where possible use bootstrap classes for styling.

Have fun,

**Comment by chelmerrox** [comment]
Thanks for the review!
